# Generated by Django 3.1.7 on 2021-03-17 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='firstName',
            field=models.CharField(default='hello', max_length=50),
        ),
        migrations.AddField(
            model_name='account',
            name='lastName',
            field=models.CharField(default='goodbye', max_length=50),
        ),
    ]
