# Generated by Django 3.1.7 on 2021-03-17 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20210317_1601'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='firstName',
            new_name='first_Name',
        ),
        migrations.RenameField(
            model_name='account',
            old_name='lastName',
            new_name='last_Name',
        ),
    ]
