# Generated by Django 3.1.7 on 2021-03-17 20:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20210317_1607'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='first_Name',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='account',
            old_name='last_Name',
            new_name='last_name',
        ),
    ]
