# Generated by Django 3.1.7 on 2021-03-23 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eods', '0004_auto_20210322_1243'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leadsheet',
            name='sent_from',
        ),
    ]
