# Generated by Django 3.1.7 on 2021-03-23 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eods', '0005_remove_leadsheet_sent_from'),
    ]

    operations = [
        migrations.AddField(
            model_name='leadsheet',
            name='adj_orthobanc',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='leadsheet',
            name='adj_orthobanc_deposited',
            field=models.BooleanField(default=False, verbose_name='Adj ortho deposited?'),
        ),
    ]
