# Generated by Django 3.1.7 on 2021-03-26 00:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eods', '0006_auto_20210323_1202'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='office',
            name='email',
        ),
    ]
