# Generated by Django 3.1.7 on 2021-03-26 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eods', '0007_remove_office_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='office',
            name='email',
            field=models.EmailField(default='nature.swarup@capstonedg.com', max_length=500),
        ),
        migrations.AddField(
            model_name='office',
            name='was_notified',
            field=models.BooleanField(default=False, verbose_name='Was the office notified?'),
        ),
    ]
