# Generated by Django 3.1.7 on 2021-03-27 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eods', '0008_auto_20210325_2014'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leadsheet',
            name='adj_carecredit',
        ),
        migrations.RemoveField(
            model_name='leadsheet',
            name='adj_carecredit_deposited',
        ),
        migrations.RemoveField(
            model_name='leadsheet',
            name='adj_greensky',
        ),
        migrations.RemoveField(
            model_name='leadsheet',
            name='adj_greensky_deposited',
        ),
        migrations.RemoveField(
            model_name='leadsheet',
            name='adj_kleer',
        ),
        migrations.RemoveField(
            model_name='leadsheet',
            name='adj_kleer_deposited',
        ),
        migrations.RemoveField(
            model_name='leadsheet',
            name='adj_lending_club',
        ),
        migrations.RemoveField(
            model_name='leadsheet',
            name='adj_lending_point',
        ),
        migrations.RemoveField(
            model_name='leadsheet',
            name='adj_lending_point_deposited',
        ),
        migrations.RemoveField(
            model_name='leadsheet',
            name='adj_orthobanc',
        ),
        migrations.RemoveField(
            model_name='leadsheet',
            name='adj_orthobanc_deposited',
        ),
        migrations.RemoveField(
            model_name='leadsheet',
            name='adj_proceed',
        ),
        migrations.RemoveField(
            model_name='leadsheet',
            name='adj_proceed_deposited',
        ),
        migrations.RemoveField(
            model_name='leadsheet',
            name='adj_text_to_pay',
        ),
        migrations.RemoveField(
            model_name='leadsheet',
            name='adj_text_to_pay_deposited',
        ),
        migrations.RemoveField(
            model_name='leadsheet',
            name='capital_accounts',
        ),
        migrations.RemoveField(
            model_name='leadsheet',
            name='capital_accounts_deposited',
        ),
        migrations.RemoveField(
            model_name='leadsheet',
            name='carecredit_code1',
        ),
        migrations.RemoveField(
            model_name='leadsheet',
            name='carecredit_code2',
        ),
        migrations.RemoveField(
            model_name='leadsheet',
            name='carecredit_code3',
        ),
        migrations.RemoveField(
            model_name='leadsheet',
            name='carecredit_code4',
        ),
        migrations.RemoveField(
            model_name='leadsheet',
            name='carecredit_code5',
        ),
        migrations.RemoveField(
            model_name='leadsheet',
            name='carecredit_gross1',
        ),
        migrations.RemoveField(
            model_name='leadsheet',
            name='carecredit_gross2',
        ),
        migrations.RemoveField(
            model_name='leadsheet',
            name='carecredit_gross3',
        ),
        migrations.RemoveField(
            model_name='leadsheet',
            name='carecredit_gross4',
        ),
        migrations.RemoveField(
            model_name='leadsheet',
            name='carecredit_gross5',
        ),
        migrations.RemoveField(
            model_name='leadsheet',
            name='credit_cards',
        ),
        migrations.RemoveField(
            model_name='leadsheet',
            name='credit_cards_deposited',
        ),
        migrations.RemoveField(
            model_name='leadsheet',
            name='direct_deposit',
        ),
        migrations.RemoveField(
            model_name='leadsheet',
            name='direct_deposit_deposited',
        ),
        migrations.RemoveField(
            model_name='leadsheet',
            name='dishita_checks',
        ),
        migrations.RemoveField(
            model_name='leadsheet',
            name='dishita_checks_deposited',
        ),
        migrations.RemoveField(
            model_name='leadsheet',
            name='greensky_code1',
        ),
        migrations.RemoveField(
            model_name='leadsheet',
            name='greensky_code2',
        ),
        migrations.RemoveField(
            model_name='leadsheet',
            name='greensky_code3',
        ),
        migrations.RemoveField(
            model_name='leadsheet',
            name='greensky_code4',
        ),
        migrations.RemoveField(
            model_name='leadsheet',
            name='greensky_gross1',
        ),
        migrations.RemoveField(
            model_name='leadsheet',
            name='greensky_gross2',
        ),
        migrations.RemoveField(
            model_name='leadsheet',
            name='greensky_gross3',
        ),
        migrations.RemoveField(
            model_name='leadsheet',
            name='greensky_gross4',
        ),
        migrations.RemoveField(
            model_name='leadsheet',
            name='ins_checks',
        ),
        migrations.RemoveField(
            model_name='leadsheet',
            name='ins_checks_deposited',
        ),
        migrations.RemoveField(
            model_name='leadsheet',
            name='kleer_code1',
        ),
        migrations.RemoveField(
            model_name='leadsheet',
            name='kleer_code2',
        ),
        migrations.RemoveField(
            model_name='leadsheet',
            name='kleer_code3',
        ),
        migrations.RemoveField(
            model_name='leadsheet',
            name='kleer_code4',
        ),
        migrations.RemoveField(
            model_name='leadsheet',
            name='kleer_code5',
        ),
        migrations.RemoveField(
            model_name='leadsheet',
            name='kleer_gross1',
        ),
        migrations.RemoveField(
            model_name='leadsheet',
            name='kleer_gross2',
        ),
        migrations.RemoveField(
            model_name='leadsheet',
            name='kleer_gross3',
        ),
        migrations.RemoveField(
            model_name='leadsheet',
            name='kleer_gross4',
        ),
        migrations.RemoveField(
            model_name='leadsheet',
            name='kleer_gross5',
        ),
        migrations.RemoveField(
            model_name='leadsheet',
            name='patient_checks',
        ),
        migrations.RemoveField(
            model_name='leadsheet',
            name='patient_checks_deposited',
        ),
        migrations.RemoveField(
            model_name='leadsheet',
            name='refund',
        ),
        migrations.RemoveField(
            model_name='leadsheet',
            name='refund_deposited',
        ),
        migrations.RemoveField(
            model_name='leadsheet',
            name='refund_email',
        ),
        migrations.RemoveField(
            model_name='leadsheet',
            name='text_to_pay1',
        ),
        migrations.RemoveField(
            model_name='leadsheet',
            name='text_to_pay2',
        ),
        migrations.RemoveField(
            model_name='leadsheet',
            name='text_to_pay3',
        ),
        migrations.RemoveField(
            model_name='leadsheet',
            name='text_to_pay4',
        ),
        migrations.RemoveField(
            model_name='leadsheet',
            name='text_to_pay_code1',
        ),
        migrations.RemoveField(
            model_name='leadsheet',
            name='text_to_pay_code2',
        ),
        migrations.RemoveField(
            model_name='leadsheet',
            name='text_to_pay_code3',
        ),
        migrations.RemoveField(
            model_name='leadsheet',
            name='text_to_pay_code4',
        ),
        migrations.AddField(
            model_name='leadsheet',
            name='care_credit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='leadsheet',
            name='care_credit_deposited',
            field=models.BooleanField(default=False, verbose_name='Carecredit Deposited?'),
        ),
        migrations.AddField(
            model_name='leadsheet',
            name='cc_amex',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='leadsheet',
            name='cc_amex_deposited',
            field=models.BooleanField(default=False, verbose_name='Amex Deposited?'),
        ),
        migrations.AddField(
            model_name='leadsheet',
            name='cc_discover',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='leadsheet',
            name='cc_discover_deposited',
            field=models.BooleanField(default=False, verbose_name='Discover Deposited?'),
        ),
        migrations.AddField(
            model_name='leadsheet',
            name='cc_mastercard',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='leadsheet',
            name='cc_mastercard_deposited',
            field=models.BooleanField(default=False, verbose_name='Mastercard Deposited?'),
        ),
        migrations.AddField(
            model_name='leadsheet',
            name='cc_visa',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='leadsheet',
            name='cc_visa_deposited',
            field=models.BooleanField(default=False, verbose_name='Visa Deposited?'),
        ),
        migrations.AddField(
            model_name='leadsheet',
            name='checks',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='leadsheet',
            name='checks_deposited',
            field=models.BooleanField(default=False, verbose_name='Checks Deposited?'),
        ),
        migrations.AddField(
            model_name='leadsheet',
            name='eft',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='leadsheet',
            name='eft_deposited',
            field=models.BooleanField(default=False, verbose_name='EFT Deposited?'),
        ),
        migrations.AddField(
            model_name='leadsheet',
            name='electronic_checks',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='leadsheet',
            name='electronic_checks_deposited',
            field=models.BooleanField(default=False, verbose_name='Electronic Checks Deposited?'),
        ),
        migrations.AddField(
            model_name='leadsheet',
            name='flips',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='leadsheet',
            name='flips_deposited',
            field=models.BooleanField(default=False, verbose_name='Flips Deposited?'),
        ),
        migrations.AddField(
            model_name='leadsheet',
            name='greensky',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='leadsheet',
            name='greensky_deposited',
            field=models.BooleanField(default=False, verbose_name='Greensky Deposited?'),
        ),
        migrations.AddField(
            model_name='leadsheet',
            name='lending_club',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='leadsheet',
            name='orthobanc',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='leadsheet',
            name='orthobanc_deposited',
            field=models.BooleanField(default=False, verbose_name='OrthoBanc Deposited?'),
        ),
        migrations.AddField(
            model_name='leadsheet',
            name='other',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='leadsheet',
            name='other_deposited',
            field=models.BooleanField(default=False, verbose_name='Other Deposited?'),
        ),
        migrations.AddField(
            model_name='leadsheet',
            name='pnc_deposit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='leadsheet',
            name='pnc_deposit_deposited',
            field=models.BooleanField(default=False, verbose_name='PNC Deposited?'),
        ),
        migrations.AddField(
            model_name='leadsheet',
            name='text2pay',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='leadsheet',
            name='text2pay_deposited',
            field=models.BooleanField(default=False, verbose_name='Text to Pay Deposited?'),
        ),
        migrations.AddField(
            model_name='leadsheet',
            name='web_cc',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='leadsheet',
            name='web_cc_deposited',
            field=models.BooleanField(default=False, verbose_name='Web Credit Card Deposited?'),
        ),
        migrations.AlterField(
            model_name='leadsheet',
            name='adj_lending_club_deposited',
            field=models.BooleanField(default=False, verbose_name='Lending Club Deposited?'),
        ),
    ]
