# Generated by Django 3.1.7 on 2021-03-28 00:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eods', '0009_auto_20210327_1801'),
    ]

    operations = [
        migrations.RenameField(
            model_name='leadsheet',
            old_name='adj_lending_club_deposited',
            new_name='lending_club_deposited',
        ),
    ]
