# Generated by Django 3.1.7 on 2021-03-28 03:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eods', '0010_auto_20210327_2010'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leadsheet',
            name='cash',
        ),
    ]
