# Generated by Django 3.1.7 on 2021-03-28 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eods', '0011_remove_leadsheet_cash'),
    ]

    operations = [
        migrations.AddField(
            model_name='leadsheet',
            name='cash',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
